INSERT INTO post (id, content, author) VALUES (1, 'Hello, World!', 'Alice');
INSERT INTO post (id, content, author) VALUES (2, 'Spring Boot is awesome!', 'Bob');
INSERT INTO post (id, content, author) VALUES (3, 'Check out this new blog post!', 'Alice');
INSERT INTO post (id, content, author) VALUES (4, 'Look at my new photo!', 'Charlie');
INSERT INTO post (id, content, author) VALUES (5, 'I love Spring Boot!', 'Alice');
INSERT INTO post (id, content, author) VALUES (6, 'I love Spring Boot!', 'Bob');
INSERT INTO post (id, content, author) VALUES (7, 'I love Spring Boot!', 'Charlie');
INSERT INTO post (id, content, author) VALUES (8, 'I love Spring Boot!', 'Alice');
INSERT INTO post (id, content, author) VALUES (9, 'I love Spring Boot!', 'Bob');
INSERT INTO post (id, content, author) VALUES (10, 'I love Spring Boot!', 'Charlie');